name: Update README with Random Quote

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch a random quote
        id: fetchquote
        run: |
          quote=$(curl -s "https://api.quotable.io/quotes/random?tags=technology,famous-quotes" | jq -r '.[0].content')
          author=$(curl -s "https://api.quotable.io/quotes/random?tags=technology,famous-quotes" | jq -r '.[0].author')
          echo "QUOTE=$quote" >> $GITHUB_ENV
          echo "AUTHOR=$author" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|<!-- QUOTE_PLACEHOLDER -->|\"$QUOTE\" - $AUTHOR|g" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Updated quote"
          git push
